### ISSUE TITLE
disconnection possible fix?

### ISSUE THREAD

**Issue by vortex91** [cabernetwork/provider_video_daddylive#10]
both internal proxy and streamlink proxy have lots of freezing dropped packets.  If i run same stream on browser there is no issue.  Also if i run same stream using kodi addon from https://github.com/mrgsi/mrgsi.github.io there is no issue.  Can this kodi addon be ported over?

**Comment by rocky4546** [comment]
No it cannot, but you will need to prove it is not having this issue on daddylive itself.  It looks like daddylive recently made some backend changes that are causing lots of dropped packets, even on its own site.  Looking at the video on DL and cabernet, I see the same dropped packets.

**Comment by vortex91** [comment]
Do you have recomended settings for your config?  defaults are not working for me.  Im on same local network using browser vs cabernet and drops are 10 times more on cabernet vs browser.

**Comment by vortex91** [comment]
cnbc usa https://dlhd.sx/stream/stream-309.php

**Comment by rocky4546** [comment]
Looks like there is an issue.  The interface has not changed, but it is throwing connection refused.  It looks like it is having a fit when requesting multiple requests at one time.  I will slow down the threads and see if that makes it work.

**Comment by rocky4546** [comment]
I looks like DL is working fine now, but I did see an issue when each stream packet was not downloading very fast.  If you want to try something, use the internal proxy and set the "Concurrent Downloads" in the DL settings to 1.  This stops parallel processing.  It also will cause more dropped packets, but if DL is now throwing exceptions when multiple requests happen at the same time, it would be better than nothing.  For now, DL is working no matter what the setting.

**Comment by vortex91** [comment]
0 simultanius streams with internal proxy works best for me. (in comparison to strealink)

**Comment by vortex91** [comment]
here is setup which works best for me
strem timeout 12
concurent downlaods 0
http time out 12
http retries 1 (for some reason 0 doesnt work properly)

based on test i have done im guessing daddy doesnt like http retries and instead like a full new request.  Value of 12 gives enough buffer time to where i get a slight hickup in video but seems to be farily smooth.

**Comment by rocky4546** [comment]
one thing we have not tried is to have it do a new http session each time.  That also may help since it looks like once it has the connection refused, it will keep doing that for the http session.  It use to be that DL liked having the same session. I'll keep working on this for the next few days.  Probably will need to add some more parameters to configure DL just right.
