### ISSUE TITLE
down or is it just me?

### ISSUE THREAD

**Issue by vortex91** [cabernetwork/provider_video_daddylive#16]
v 1.22 

2024-06-02 03:30:29
error: Unable to open URL: https://ddh2.onlinehdhls.ru/ddh2/premium347/tracks-v1a1/mono.m3u8 (403 Client Error: Forbidden for url: https://ddh2.onlinehdhls.ru/ddh2/premium347/tracks-v1a1/mono.m3u8)
2024-06-02 03:30:29
error: Unable to open URL: https://ddh2.onlinehdhls.ru/ddh2/premium347/tracks-v1a1/mono.m3u8 (403 Client Error: Forbidden for url: https://ddh2.onlinehdhls.ru/ddh2/premium347/tracks-v1a1/mono.m3u8)

**Comment by rocky4546** [comment]
They made more changes.  version 23 works if you reset the channel list.

**Comment by fragtion** [comment]
Hi. Same issue with version 25 now for me, pls fix :)

**Comment by vortex91** [comment]
its working for me.  Not sure if its a specific channel?  try different ones?

**Comment by fragtion** [comment]
you're right. looks like my vps provider was blocked. working fine on another host. thanks for checking
