### ISSUE TITLE
All channels suddenly not working.

### ISSUE THREAD

**Issue by heyimjake** [cabernetwork/provider_video_daddylive#18]
![image](https://github.com/cabernetwork/provider_video_daddylive/assets/70820561/2a233c50-5b0f-467b-8274-53473e1bacc4)
I've reset and pulled new channel data, have tried from multiple clients, nothing seems to work.
This is entirely sudden, no changes made.
Hosted on Ubuntu 22.04.4

**Comment by rocky4546** [comment]
Duplicate #17
