### ISSUE TITLE
Automatically update plugins

### ISSUE THREAD

**Issue by booog35** [cabernetwork/provider_video_daddylive#19]
I apologize if this is feature has already been implemented. Cabernet has a nice feature of notifying you when a plugin update is available. It would be great if there was an configuration to automatically download and "install" this update. Thinking about the current Daddylive plugin m3u search changes.

**Comment by athaller** [comment]
I might refactor this myself and just put a loop in it for the time being with a fallback to a git repo that can be updated without having to update the user end plugin..

TLDR;

if re == "" || null is re -> continue and check next regex.. as a fallback for the loops, make a http call to raw.github.com/cabernetwork/constants-repo/plugin_daddylive_regex.txt to get the latest regex... thus allowing for a fallback that can be community contributed and easily updated without a full plugin update

sorry if its confusing, little sleep at the moment so will make a reminder to look at this tomorrow
