### ISSUE TITLE
Daddylive streaming not working via plex



### ISSUE THREAD

**Issue by riyaaz2016** [cabernetwork/provider_video_daddylive#20]
Issue streaming channels via daddylive addon with plex.

I am new to Cabernet, and recently had it setup. I use cabernet docker, with plex docker running off intel nuc 10th gen with ubuntu server 24.04 lts.

I've followed all the instructions, and actually had streaming working fine from plex. Then all of a sudden after a few daddylive addon updates it just appeared to stop working. When attempting to stream from plex, I get " There was an error while attempting to tune the selected channel. Please check your connection and try again."  I am running cabernet 0.9.15.00-RC01 and daddylive addon v0.1.31 which is latest one. I've restarted app, plug-ins, refreshed channels and epg and still no luck. Bounced server etc..... 

I've tried streaming same channels from plex mobile app on android, plex on Samsung TV, plex on chrome browser via windows pc, and androidtv box plex app all show same error message. 

When checking cabernet logs after enabling debug I see the below?

2024-07-10 22:41:19,164-INFO:decorators HTTPError in function M3U8GetUriData.get_uri_data(), retrying 234 403 Client Error: Forbidden for url: https://key2.mizhls.ru/wmsxx.php?name=premium594&number=1 https://key2.mizhls.ru/wmsxx.php?name=premium594&number=1
2024-07-10 22:41:19,173-DEBUG:m3u8_queue Reloading m3u8 stream queue 234
2024-07-10 22:41:19,175-DEBUG:internal_proxy No Video Stream from Provider 234 https://ddy1.mizhls.ru/ddy1/premium594/tracks-v1a1/2024/07/10/20/40/56-04000.ts

Below is copy of my config file:
[loggers]
keys = root

[logger_root]
level = TRACE
handlers = filehandler,loghandler

[handlers]
keys = loghandler, filehandler

[formatters]
keys = extend,simple

[handler_filehandler]
enabled = True
level = DEBUG
formatter = extend
class = lib.common.log_handlers.MPRotatingFileHandler
args = (os.getenv('LOGS_DIR','data/logs')+'/cabernet.log', 'a', 10000000, 10)

[handler_loghandler]
enabled = True
level = DEBUG
class = StreamHandler
formatter = extend
args = (sys.stdout,)

[formatter_extend]
format = %(asctime)s-%(levelname)s:%(module)s %(message)s

[formatter_simple]
format = %(levelname)s:%(module)s %(message)s

[main]
uuid = 4DA30C38-3B67-11EF-A80F-0242AC110002
maintenance_mode = False

[hdhomerun]
hdhr_id = 105E40F0
disable_hdhr = True

[tvguide]
enabled = True

[m3u]
hdhr_id = 1057973D
enabled = True

[daddylive]
hdhr_id = 105C1D9F
enabled = True
player-tuner_count = 10
epg-plugin = ALL

[display]
display_level = 3-Advanced

[epg]
epg_use_channel_number = True
epg_prettyprint = True

[daddylive_default]
label = DaddyLive Instance
enabled = True
player-stream_type = internalproxy

[tvguide_default]
label = TVGuide Instance
enabled = True
default_zone = Central

Please help if can assist.

**Comment by riyaaz2016** [comment]
Did anything perhaps change... I checks this morning and see now sky sports NZ channels are working fine! I didn't change anything my end to my setup, just started working all of a sudden.

Epg works fine and streaming those sports channels.

Any idea what issue was?

**Comment by drysun2008** [comment]
It was not working for me either previously and when I ran the logs in trace mode it indicated the server with the encryption keys was returning a http 403 code for me. Seems like it no longer gives me a 403 error code, so guess something was updated on the daddylive servers (strangely enough kodi worked during the time when cabernet was not). Makes me wonder if they had some cloudflare or other protection going on temporarily.

`2024-07-09 23:08:21,734-INFO:decorators HTTPError in function M3U8GetUriData.get_uri_data(), retrying 3244 403 Client Error: Forbidden for url: https://key2.mizhls.ru/wmsxx.php?name=premium343&number=1 https://key2.mizhls.ru/wmsxx.php?name=premium343&number=1`

**Comment by riyaaz2016** [comment]
Thanks for sharing, saw same logs propping up my side via debug......

At least it's working now! 😁

Do you perhaps know of any other good epg xml online sites to get guides from? I am looking for one with UK channels, in particular the sports channels. Ones from https://i.mjh.nz/ do not seem to have these ones or even movie channels which is odd..

**Comment by drysun2008** [comment]
I'm in the US, so not sure. I use emby and plex and they both have built in EPGs (if you are premium or whatever they call it) and just map the channels to a cable service instead of using an xml guide.

**Comment by riyaaz2016** [comment]
Thanks will play around in plex and see
