### ISSUE TITLE
Share daddylive dvr via plex with home user? 

### ISSUE THREAD

**Issue by riyaaz2016** [cabernetwork/provider_video_daddylive#21]
Does anyone know how to share plex dvr with a Home User? I have an Intel nuc 10th gen which runs Ubuntu 24.04 lts with plex and cabernet via docker containers. I then use daddylive addon via cabernet plex dvr for streaming which works great. I do though want to get a friend access so he too access and watch dvr from his account as a Home User linked to my main plex account with me being Admin and having plex pass. When he's logged into plex in live TV all he sees is plex channels not other managed sources--> my dvr feed? Anyone got this working? All access has already been granted via live TV and DVR access to user from my end as Admin but still only shows Plex channels as only source his side under Live TV.

What I noticed is that if I log in as my account as admin then I switch user to his account and then access live TV it shows the dvr source and stream TV channels fine....... Mind you my friend also has plex pass so rules that out too. Any idea on this one.....

**Comment by drysun2008** [comment]
That's really a plex question and better asked in the plex reddit or on their forums. You may not have granted them access to the live tv/DVR under the plex home-user-restrictions. if they have access they should be able to see/add your server as a source for live tv. If you need more help you should ask over the other places stating that an invited user can't access your live tv/dvr.

**Comment by riyaaz2016** [comment]
Thanks appreciate the feedback, I agree more plex related. Will give this a shot and see otherwise log a query to plex forum.
