### ISSUE TITLE
Scan all 3 players on Daddylive

### ISSUE THREAD

**Issue by titelheld** [cabernetwork/provider_video_daddylive#32]
Is it possible to scan all three players on daddy live to make sure there will be at least one working stream per channel?

I was thinking perhaps it is possible to run the daddylive plugin three times each set to to adifferent player and then combinging them in tvheadend...

or is there a smarter way to go about this?

**Comment by rocky4546** [comment]
First, player 1 and 2 are the same, so you only need two instances.  What I did was create an additional instance in the config.ini file.  Then, you can set one instance to player 1 and the other to player 3.  Next, go to the channel editor and set each channel to either 1 or 3 for DL.  For my config.ini, I left the main instance as is (but changed its instance name to DaddyLive Instance P3). The second instance I added as

> [daddylive_p1]
> label = DaddyLive Instance P1
> enabled = True

That is basically how you can do it.  If a channel is an issue on P3, I can change the instance to P1 to see if it works better for the short.

**Comment by titelheld** [comment]
I am a bit surprised that you said that player 1 and 2 are the same, after all they have different urls. 

p1=stream
p2=cast
p3=watch

and i saw (perhaps this is new on DL) that some channels have 5 players

p4=player
p5=casting

**Comment by fragtion** [comment]
> I added the p3 daddy live instance but when pulling the channels the channel editor only shows channels for the default instance my p3 instance is no where to be found and the m3u from http://mytvserverip:6077/daddylive/p3/channels.m3u remains empty. :(
> 
> Do any of the duplicate filtering functions have to be disabled for this to work?

I have the same issue. Please update instructions
