### ISSUE TITLE
DaddyLive added a ton of new channels

### ISSUE THREAD

**Issue by Nostradamus1973** [cabernetwork/provider_video_daddylive#6]
Good Morning Everyone,

I've kinda been sitting on this one for a few days to see if it self corrects itself, OR, to see if someone posts a similar issue; given that neither has happened, here I am.
I noticed a large dump of channels within Daddylive approximately 2 days ago, with this came lots of cool channels and the absence of an EPG, I'm not sure if I'm missing something or quite possibly the DaddyLive Plugin needs updating.
Logs are attached.

Thank you and have a nice day.
[cabernet.log](https://github.com/cabernetwork/cabernet/files/11975058/cabernet.log)

**Comment by Nostradamus1973** [comment]
Update: 
I did a squeaky clean install only carrying over my docker-compose.yaml and config.ini and I'm still seeing the same thing.

**Comment by rocky4546** [comment]
Changed from 309 to 681 channels, so I will take a look and see which we can link with our EPG.  There is also ones that has disappeared, so will also remove those from the link list.

**Comment by Nostradamus1973** [comment]
That's fantastic, however, it  sounds like a very tedious task for one person alone. 

Can I help somehow?

If  you show me how I can chase down some of the links  and we can split the workload.

**Comment by rocky4546** [comment]
I have the list paired down to 90 new channels with possible guide data. The hard ones are the local channels.  If you want to help, contact me at discord rocky4546#8998.

**Comment by Nostradamus1973** [comment]
Okay great, glad to help, I sent a request.

**Comment by rocky4546** [comment]
looks like daddylive is having some copyright issues starting today around lunch time. stay tuned.

**Comment by rocky4546** [comment]
Initial version 0.1.9 has been released.  It has most of the USA channels with TVGuide data, however, more is needed.  For now, this should work for the previous set plus some extras.

**Comment by Nostradamus1973** [comment]
That's great news!
Thanks for the update Rocky, I'll check out the release.
ttyl :)
