### ISSUE TITLE
Daddy live changed url again. Unable to pull channel list. 

### ISSUE THREAD

**Issue by titelheld** [cabernetwork/provider_video_daddylive#8]
it seems they changed the url again... this message is from their official discord. 

@everyone All Streams listed on https://daddylivehd.com | Join Telegram : https://t.me/daddylivehd || Discord : https://discord.gg/SgbjFVn6th || Facing Issue Ping in Chat Mods & Admin Help! | Always use Official! URL beware of Clones!

‘hope this is a quick fix. 🌹

**Comment by rocky4546** [comment]
running tests, will be out in a short.

**Comment by titelheld** [comment]
Thanks for the quick reply. I was also looking at the translations.py but couldn’t figure out how to generate this cryptic code to put in the url

**Comment by rocky4546** [comment]
0.1.11 updated.  Just run the check for updates and it should find it in the plugins list.

**Comment by titelheld** [comment]
giving it a try now :)

**Comment by titelheld** [comment]
working great, thanks for the quick fix. 🌹 🌸
