### ISSUE TITLE
A possible idea regarding the 1-30 channels on daddylive

### ISSUE THREAD

**Issue by AFrameWorker** [cabernetwork/provider_video_daddylive#9]
These channels change quite frequently, and are not normally accessible via the cabernetwork daddylive plugin, however it would be nice if a new daddylive"extras" plugin would be made, which can grab these 1-30 channels plus possibly some others if there are any. Having this as as separate plugin is nice because then I can allow the scheduler scan daddylive for these 1 to 30 channels more often, without having to rescan the entirety of daddylive over and over.

What do you think of this?

**Comment by rocky4546** [comment]
duplicate #1

**Comment by AFrameWorker** [comment]
Oh oops, my bad. How did I not see that one?
